"""Generate identical per-language test vectors from catalog/problems.json.

Python and the catalogue test harness read the JSON directly. Java, C++ and
Rust compile in the same vectors via generated source files so every language
is tested against byte-for-byte the same inputs and expected outputs.

Usage::

    python engine/gen_tests.py            # regenerate all three
    python engine/gen_tests.py --check    # fail if any file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog" / "problems.json"

JAVA_OUT = ROOT / "languages" / "java" / "src" / "ads" / "gen" / "TestData.java"
CPP_OUT = ROOT / "languages" / "cpp" / "tests" / "generated_test_data.hpp"
RUST_OUT = ROOT / "languages" / "rust" / "src" / "gen" / "mod.rs"

ALGORITHM_IDS = [
    "two_sum",
    "binary_search",
    "merge_sort",
    "quick_sort",
    "max_subarray",
    "lcs",
    "knapsack_01",
    "edit_distance",
    "graph_bfs",
    "graph_dfs",
]
STRUCTURE_IDS = ["stack", "queue", "linked_list", "bst", "trie", "min_heap"]


def load_catalog() -> dict:
    with CATALOG.open() as handle:
        return json.load(handle)


def _ident(value: str) -> str:
    return value.replace("-", "_")


def _cpp_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _rust_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def generate_java(catalog: dict) -> str:
    lines = [
        "// Generated by engine/gen_tests.py from catalog/problems.json.",
        "// Do not edit by hand.",
        "package ads.gen;",
        "",
        "public final class TestData {",
        "    private TestData() {",
        "    }",
        "    public static final String[][][] ALGORITHMS = {",
    ]
    algos = {a["id"]: a for a in catalog["algorithms"]}
    for idx, algo_id in enumerate(ALGORITHM_IDS):
        cases = algo_id in algos and algos[algo_id]["cases"]
        assert cases is not None, f"missing algorithm {algo_id}"
        lines.append(f"        new String[][] {{  // {algo_id}")
        for case in cases:
            lines.append(f'            {{"{case["in"]}", "{case["out"]}"}},')
        lines.append("        },")
    lines.append("    };")
    lines.append("    public static final String[][][] STRUCTURES = {")
    structs = {d["id"]: d for d in catalog["data_structures"]}
    for struct_id in STRUCTURE_IDS:
        entry = structs[struct_id]
        cases = entry["cases"]
        lines.append(f"        new String[][] {{  // {struct_id}")
        for case in cases:
            ops = ",".join(case["ops"])
            lines.append(f'            {{"{ops}"}},')
        lines.append("        },")
    lines.append("    };")
    lines.append("}")
    return "\n".join(lines) + "\n"


def generate_cpp(catalog: dict) -> str:
    lines = [
        "// Generated by engine/gen_tests.py from catalog/problems.json.",
        "// Do not edit by hand.",
        "#pragma once",
        "",
        '#include <string>',
        "#include <vector>",
        "",
        "namespace ads::gen {",
        "",
        "inline const std::vector<std::vector<std::vector<std::string>>> ALGORITHMS = {",
    ]
    algos = {a["id"]: a for a in catalog["algorithms"]}
    for algo_id in ALGORITHM_IDS:
        cases = algos[algo_id]["cases"]
        lines.append(f"    {{  // {algo_id}")
        for case in cases:
            lines.append(
                f'        {{{_cpp_string(case["in"])}, {_cpp_string(case["out"])}}},'
            )
        lines.append("    },")
    lines.append("};")
    lines.append(
        "inline const std::vector<std::vector<std::vector<std::string>>> STRUCTURES = {"
    )
    structs = {d["id"]: d for d in catalog["data_structures"]}
    for struct_id in STRUCTURE_IDS:
        cases = structs[struct_id]["cases"]
        lines.append(f"    {{  // {struct_id}")
        for case in cases:
            joined = ",".join(case["ops"])
            lines.append(f"        {{{_cpp_string(joined)}}},")
        lines.append("    },")
    lines.append("};")
    lines.append("}  // namespace ads::gen")
    return "\n".join(lines) + "\n"


def generate_rust(catalog: dict) -> str:
    lines = [
        "// Generated by engine/gen_tests.py from catalog/problems.json.",
        "// Do not edit by hand.",
        "",
        "/// [(algorithm_id_index, [(input, expected), ...]), ...]",
        "pub const ALGORITHMS: &[(&str, &[(&str, &str)])] = &[",
    ]
    algos = {a["id"]: a for a in catalog["algorithms"]}
    for algo_id in ALGORITHM_IDS:
        cases = algos[algo_id]["cases"]
        lines.append(f"    ({_rust_string(algo_id)}, &[")
        for case in cases:
            lines.append(
                f"        ({_rust_string(case["in"])}, {_rust_string(case["out"])}),"
            )
        lines.append("    ]),")
    lines.append("];")
    lines.append('/// [(structure_id_index, [comma-joined op token list, ...])]')
    lines.append("pub const STRUCTURES: &[(&str, &[&str])] = &[")
    structs = {d["id"]: d for d in catalog["data_structures"]}
    for struct_id in STRUCTURE_IDS:
        cases = structs[struct_id]["cases"]
        lines.append(f"    ({_rust_string(struct_id)}, &[")
        for case in cases:
            joined = ",".join(case["ops"])
            lines.append(f"        {_rust_string(joined)},")
        lines.append("    ]),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def write_file(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    stale = path.exists() and path.read_text() != content
    path.write_text(content)
    return f"{'M' if stale else ' '}  {path.relative_to(ROOT)}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if files are stale")
    args = parser.parse_args()

    catalog = load_catalog()
    targets = [
        (JAVA_OUT, generate_java(catalog)),
        (CPP_OUT, generate_cpp(catalog)),
        (RUST_OUT, generate_rust(catalog)),
    ]
    changed = False
    for path, content in targets:
        status = write_file(path, content)
        if status.startswith("M"):
            changed = True
        print(status)
    if args.check and changed:
        print("ERROR: generated vectors are stale — run engine/gen_tests.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())